SET client_encoding = 'UTF8';
-- База викторины v2 (RuBQ, обманки по семантическому типу — осмысленные)
DELETE FROM rb_quiz WHERE points=1;  -- заменяем стартовую базу, вопросы админов (points>=2) сохраняем
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал роман «Хижина дяди Тома»?','["Орест Кипренский", "Г. Бичер-Стоу", "Алексей Сидоров", "Василий Iii"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор пьесы «Ромео и Джульетта»?','["Шекспир", "Тургенев", "Милн", "Ф. И. Тютчев"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется столица Румынии?','["Жодино", "Бухарест", "Благовещенск", "Лиссабон"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит остров Таити?','["Турция", "Новая Зеландия", "Франции", "Казахстан"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто режиссер фильма "Бриллиантовая рука"?','["Александр Журбин", "Л.Гайдай", "Эрих Мария Ремарк", "Булычев"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежат Канарские острова?','["Испания", "Франция", "Аргентина", "Австрия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какое современное государство занимает территорию, на которой находился древний ассирийский город Ниневия?','["Ирак", "Латвия", "Мьянма", "Грузия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране впервые появилась игра в гольф?','["Швейцария", "Камбоджа", "Шотландия", "Кения"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Каким видом спорта увлекался президент РФ В.В.Путин?','["Дзюдо", "Фехтование", "Футбол", "Хоккей"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор исторического романа ''Княжна Тараканова''?','["П. И. Чайковский", "Филипп Добрый", "Камиль Сен-Санс", "Г. П. Данилевский"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('С какой страной связано название Блистательная Порта?','["Мексика", "Англия", "Турция", "Китай"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор музыки к фильму "Александр Невский"?','["С. Прокофьев", "Иосиф Хейфиц", "Фома Фомич Мекензи", "Иероним Босх"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране живут кхмеры?','["Шри-Ланка", "Саудовская Аравия", "Швейцария", "Камбоджа"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится гора Эверест?','["Непал", "Панама", "Украина", "Афганистан"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится город Семипалатинск?','["Болгария", "Ирак", "Казахстан", "Афганистан"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находятся две великие реки – Тигр и Евфрат?','["Кения", "Египет", "Ирак", "Ангола"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком американском штате находится Большой Каньон?','["Кливленд", "Тюрингия", "Аризона", "Милан"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта прославился Е. Кафельников?','["Теннис", "Бейсбол", "Дзюдо", "Хоккей"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком государстве находится город Сент-Питерсберг?','["Сша", "Голландия", "Шри-Ланка", "Афганистан"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком польском городе зародилось движение "Солидарность"?','["Чикаго", "Женева", "Гданьск", "Благовещенск"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком штате Сша расположена самая длинная пещера в мире (530 км) с забавным названием Флинт-Мамонтова?','["Мальмё", "Лондон", "Уэст-Мидлендс", "Кентукки"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется административный центр штата Аляска?','["Нево", "Мбабане", "Кременчуг", "Джуно"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется столица Камбоджи?','["Пномпень", "Воткинск", "Генуя", "Сакраменто"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город на черноморском побережье назывался Кафа?','["Лондон", "Юта", "Кентукки", "Феодосия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город расположен на южном берегу пролива Золотые Ворота?','["Мадрид", "Лондон", "Керчь", "Сан-Франциско"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является административным центром штата Нью-Йорк?','["Кигали", "Бухарест", "Таллин", "Олбани"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Нигерии?','["Страсбург", "Воткинск", "Монтрё", "Абуджа"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит авиакомпания "klm"?','["Англия", "Голландия", "Афганистан", "Россия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какую стезю избрал на пятом десятке француз Мишель де Монтень, вдоволь посражавшись на стороне Генриха Iv, кем он стал?','["Нотариусом", "Царем Эпира", "Пианист", "Философ"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кому принадлежат слова "И ты, Брут"?','["Александр Дюма", "Цезарю", "Ф. И. Тютчев", "Агата"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кому принадлежат слова: "Я мыслю, следовательно существую"?','["Александр Дюма", "Франко Проспери", "Елизавета Петровна", "Декарт"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор произведения "Ученые женщины"?','["Харальд Iii", "Мольер", "Гауф", "Кубрик"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор романа "Спартак"?','["Джованьоли", "Пилат и другие", "Харальд Iii", "У Чэнъэнь"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал повесть-сказку "Приключения Пиноккио"?','["Лонгфелло", "Коллоди", "Лундгрен", "Бабель"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал поэму "Потерянный рай"?','["Алексей Тевкелев", "Мильтон", "Карл Павлович Брюллов", "Константин Маковский"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал поэму "Черный человек"?','["Джоаккино Россини", "Лев Кассиль", "Есенин", "Виктор Васнецов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал сказку "Карлик-Нос"?','["Гауф", "Герберт Джордж Уэллс", "Филипп Добрый", "Шекспир"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто плавал на папирусной лодке "Ра" и на плоту "Кон-Тики"?','["Кэти Перри", "Хейердал", "Гектор Берлиоз", "Томас Винтерберг"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто придумал Алису Селезневу?','["Тургенев", "Булычев", "Ридли Скотта", "Ария"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто придумал комиссара Мегрэ?','["Эмили Бронте", "Сименон", "Алексей Учитель", "Корней Чуковский"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто придумал персонаж по имени Анастасия Каменская?','["Р.Брэдбери", "Л.Гайдай", "Маринина", "Эмили Бронте"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто сочинил "Танец с саблями"?','["Август Хорьх", "Айзек Азимов", "Хачатурян", "Соловьев-Седой"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Столицей какой республики является Тегусигальпа?','["Ирак", "Пакистан", "Гондурас", "Швейцария"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто сказал "И ты, Брут"?','["Григорий Засекин", "Бабель", "Карл Бенц", "Цезарь"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится город Брянск?','["Россия", "Китай", "Камбоджа", "Ангола"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется город в Сша, где расположен всемирно известный Гарвардский университет?','["Таганрог", "Кембридж", "Махачкала́", "Остин"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой художник заставил запорожцев написать письмо турецкому султану?','["Пушкин", "Репин", "Кэти Перри", "Казимир Северинович Малевич"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране город Бангкок?','["Гондурас", "Тайланд", "Ирландия", "Пакистан"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится Афон – святая гора?','["Палау", "Греция", "Франция", "Ирландия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой земле Германии находится старинный город Веймар, где расположены музеи И. В. Гете, И. Ф. Шиллера и Ф. Листа?','["Сан-Франциско", "Токио", "Юта", "Тюрингия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился Людвиг ван Бетховен?','["Лондон", "Олбани", "Бонн", "Мекка"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Откуда родом был великий русский изобретатель-самоучка Иван Петрович Кулибин?','["Нижний Новгород", "Блумфонтейн", "Лондон", "Москва-река"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой писатель-фантаст придумал три закона робототехники?','["Сергей Юткевич", "Сименон", "Айзек Азимов", "Ханс Кристиан Андерсен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит остров Мадейра, давший название крепкому вину мадере?','["Грузия", "Греция", "Ирландия", "Португалии"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был знаменитый грек Аристотель, который жил в IV веке до н.э.?','["Джимми Стюарт", "Художник", "Философом", "Шут"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор строк: "Белеет парус одинокий..."?','["Александр Дюма", "Квентин Тарантино", "М.Ю.Лермонтов", "Коллоди"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей республики Бурятия?','["Улан-Удэ", "Веллингтон", "Степанакерт", "Таганрог"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Чувашии?','["Алабама", "Чебоксары", "Гаага", "Оттава"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране на население наводили ужас тонтон-макуты?','["Австралия (Сидней)", "Перу", "Корея", "Гаити"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называлась столица государства ацтеков?','["Блумфонтейн", "Ситка", "Теночтитлан", "Амьен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто создал сайт в Контакте?','["Пол Анка", "Бетховен", "Павел Дуров", "Олег Семёнович Кваша"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежат Шантарские острова?','["Мексика", "Швеция", "Россия", "Великобритания."]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто из великих художников Возрождения расписывал Сикстинскую капеллу Ватикана?','["Микеланджело", "Александр Журбин", "Лундгрен", "Guns N'' Roses"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является административным центром (столицей) штата Техас?','["Остин", "Ижевск", "Сакраменто", "Академия художеств"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой из городов является столицей Швейцарской конфедерации?','["Екатеринбург", "Шираз", "Ленинград", "Берн"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто создал Лестерский кодекс - тетрадь научных работ, которую Билл Гейтс приобрел за 30 миллионов долларов?','["Леонардо да Винчи", "Пол Анка", "Андрей Кончаловский", "Гектор Берлиоз"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал сказку "Спящая царевна"?','["Томас Манн", "В.Даль", "В. А. Жуковский", "Тургенев"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране расположен город Антверпен?','["Бельгия", "Ирландия", "Португалия", "Саудовская Аравия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране в 1960 году Сиримаво Бандаранаике стала первой женщиной премьер-министром?','["Шри-Ланка", "Грузия", "Польша", "Греция"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родилась известная актриса Фаина Раневская?','["Махачкала́", "Франкфорт", "Аргентина", "Таганрог"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился пророк Мухаммед (Магомет)?','["Константинополь", "Спартак", "Мекка", "Канберра"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где правит королевский дом Бернадотов?','["Австралия", "Таиланд", "Швеция", "Латвия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком регионе России находится старинный город Сарапул?','["Южная Дакота", "Брюссель", "Одесская", "Удмуртия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей штата Аляска?','["Джуно", "Яунде", "Ахен", "Москва-река"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Сыном какой страны был Эдмунд Хиллари, первым вместе с шерпом Н. Тенцингом покорившим Эверест?','["Австралия", "Испания", "Саудовская Аравия", "Новая Зеландия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе расположен музей "Прадо"?','["Архангельская", "Юта", "Мадрид", "Нью-Йорк"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится Танталова пещера?','["Греция", "Бельгия", "Австрия", "Иордания"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая группа записала музыкальный альбом "Актриса Весна"?','["Шарль Бодлер", "Братьями Гурьевыми", "Ддт", "Сергей Тимофеевич Аксаков"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой композитор написал первую советскую рок-оперу «Орфей и Эвридика»?','["Дмитрий Дмитриевич Шостакович", "Иван Андреевич Крылов", "Лонгфелло", "Александр Журбин"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой художник был подвергнут критике французского высшего общества за скандальный "Портрет мадам Икс"?','["Казимир Северинович Малевич", "Сергей Сергеевич Прокофьев", "Гамлет", "Джон Сингер Сарджент"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал музыку к песне "Подмосковные вечера"?','["Андрей волконский", "Стивен Спилберг", "Соловьев-Седой", "В.Даль"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто организовал зарубежные "русские сезоны", прославившие в начале XX века русский балет?','["Эмили Бронте", "Сергей Юткевич", "Дягилев", "Алексей Сидоров"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит остров Эльба-место ссылки Наполеона?','["Италия", "Во Франции в", "Соединенные Штаты Америки", "Финляндия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится национальный парк Банф?','["Швейцария", "Болгария", "Канада", "Бельгия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Каким видом спорта профессионально занимался известный тенор Зураб Соткилава?','["Футбол", "Бейсбол", "Стрельба из лука", "Хоккей"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит архипелаг Бокас-дель-Торо, на котором проходят съемки "Последнего героя"?','["Панама", "Испания", "Венгрия", "Во Франции в"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор музыкальной фантазии «Карнавал животных»?','["Академия художеств", "Айзек Азимов", "Камиль Сен-Санс", "Юрием Всеволодовичем"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране многие годы бесчинствовала левацкая террористическая организация "Сендеро Луминосо"?','["Перу", "Саудовская Аравия", "Болгария", "Танзания"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране течет река Оранжевая?','["Россия", "Юар", "Во Франции в", "Ангола"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране расположен храмовый комплекс Ангкорвоат?','["Египет", "Камбоджа", "Венесуэла", "Франция"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит домен высшего уровня .co?','["Аргентина", "Колумбия", "Испания", "Мьянма"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор книги "Шевалье де Сент-Эрмин"?','["Александр Дюма", "Ридли Скотта", "Бабель", "Иероним Босх"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Гражданином какой страны был открыватель пенициллина Александр Флеминг?','["Ливия", "Великобритания.", "Венгрия", "Монголия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто из отечественных режиссёров, снимавших фильмы по романам А.Дюма, поставил киноленту "Узник замка Иф"?','["Адольф Дасслер", "Г. Бичер-Стоу", "Г.Юнгвальд-Хилькевич", "Цезарю"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал оперу Евгений Онегин?','["Николая Михайловича Карамзина", "Кэти Перри", "П. И. Чайковский", "Л. Кулиджанов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является центром Уральского федерального округа?','["Кёнигсхайн-Видерау", "Неаполь", "Екатеринбург", "Кембридж"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Австралии?','["Женева", "Нево", "Канберра", "Тхимпху"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится одна из наиболее сохранившихся ископаемых формаций Бержес-Шейл?','["Финляндия", "Канада", "Лаос", "Монголия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Кирибати?','["Олбани", "Грац", "Южная Тарава", "Екатеринбург"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Свазиленда?','["Мар-дель-Плата", "Великобритания", "Мбабане", "Сакраменто"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится гора Косцюшко?','["Австралия", "Шотландия", "Польша", "Камбоджа"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране родился танец Фламенко?','["Гаити", "Саудовская Аравия", "Израиль", "Испания"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находятся Карлсбадские пещеры?','["Франции", "Сша", "Португалии", "Колумбия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране стоит известный памятник «Воину-освободителю»?','["Палау", "Германия", "Россия", "Куба"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит домен высшего уровня .nz?','["Никарагуа", "Сша", "Новая Зеландия", "Тайланд"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится Мекка?','["Саудовская Аравия", "Кения", "Швейцария", "Италия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал роман "На маяк"?','["Вирджиния Вулф", "Декарт", "Гамлет", "Джим Кэрри"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Нагорно-Карабахской Республики?','["Сакраменто", "Антананариву", "Степанакерт", "Каракас"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит домен высшего уровня .mo?','["Пенсильвания", "Макао", "Оренбургская", "Архангельская"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе пребывает Международный суд Оон?','["Таллин", "Гаага", "Каракас", "Абуджа"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал картину "Сад земных наслаждений"?','["Тим Бёртон", "Иероним Босх", "Бетховен", "Сименон"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране одно время правили сандинисты?','["Ирак", "Никарагуа", "Корея", "Ватикан"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто рассказал о своей первой работе в повести «Записки на манжетах»?','["Александр Журбин", "Алексей Сидоров", "Михаил Булгаков", "Роберт Земекис"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежат Азорские острова?','["Испания", "Ангола", "Португалии", "Бельгия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал рассказ "Бурмистр"?','["Тургенев", "Малевич", "Л.Гайдай", "Джим Кэрри"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал "Лестерский кодекс" который в 1994 году купил Бил Гейтс за более чем 30 миллионов долларов?','["Владимиром Святославичем", "Eurythmics", "Леонардо Да Винчи", "Р. Шекли"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Северной Ирландии?','["Белфаст", "Брюссельский столичный регион", "Мекка", "Вифлеем"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется столица Кампучии?','["Лиссабон", "Гданьск", "Братислава", "Пномпень"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('К какой стране принадлежит производитель Bmw?','["Никарагуа", "Ирак", "Великобритания.", "Германия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял короткометражку «Когда казаки плачут» по мотивам «Донских рассказов» Михаила Шолохова?','["Евгений Моргунов", "Алексей Тевкелев", "Иероним Босх", "Григорий Засекин"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране законодательную власть осуществляет кнессет?','["Турция", "Португалии", "Израиль", "Лян"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей государства Руанда?','["Кигали", "Веллингтон", "Таганрог", "Севилья"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая группа принимала участие в съёмках фильма Алексея Балабанова «Брат»?','["Цезарь", "Леонардо Да Винчи", "Наутилус Помпилиус", "Пол Анка"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой из Александровых написал музыку, которая теперь является гимном России?','["Александр Васильевич", "Киитиро Тоёда", "Йозеф Гайдн", "Лев Кассиль"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был основателем компании "Audi"?','["Август Хорьх", "Джоаккино Россини", "Иероним Босх", "Дягилев"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является режиссером скандального телесериала «Школа»?','["Джеймс Камерон", "Гауф", "Алексей Пажитнов", "Валерия Гай-Германика"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране действует террористическая организация с аббревиатурой Эта?','["Сша", "Тайланд", "Испания", "Грузия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране изобрели блюдо ризотто?','["Уругвай", "Италия", "Ссср", "Монголия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Каким видом единоборства виртуозно владеет Стивен Сигал?','["Бейсбол", "Хоккей с шайбой", "Айкидо", "Теннис"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор картины "Цветы зла?','["Джим Кэрри", "Шарль Бодлер", "Харальд Iii", "Арам Ильич Хачатупян"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был по профессии Ласло Йозеф Биро, изобретатель шариковой ручки?','["Журналист", "Джим Кэрри", "Философ", "Певицей"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком пригороде Санкт-Петербурга можно полюбоваться Янтарной комнатой?','["Нью-Йорк", "Иерусалим", "Пушкин.", "Шанхай"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор музыкальной пьесы "Ученик чародея"?','["Поль Дюка", "Людвиг Витгенштейн", "Хейердал", "Лундгрен"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является административным центром Амурской области?','["Благовещенск", "Абуджа", "Бужумбура", "Эдинбург"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был по профессии Льюис Кэрролл, автор сказок об Алисе?','["Скрипка", "Джимми Стюарт", "Математиком", "Философом"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой стране принадлежит домен высшего уровня .ao?','["Ирак", "Панама", "Ангола", "Франции"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране прошли зимние Олимпийские игры 2006 года?','["Украина", "Лян", "Гаити", "Италия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто основал компанию "Опель"?','["Эсхил", "Кубрик", "Хейердал", "Адам Опель"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится город Бухара?','["Уругвай", "Узбекистан", "Канада", "Никарагуа"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором романа "угрюм-река"?','["Маринина", "Роберт Земекис", "Шишков В", "Карл Павлович Брюллов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто поставил знаменитый японо-советский фильм "Дерсу Узала"?','["Мадонна", "Пол Анка", "Акира Куросава", "Михаил Нестеров"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор памятника И.а. Крылову в Летнем саду Санкт-Петербурга?','["Г. Бичер-Стоу", "Людвиг Витгенштейн", "Black Sabbath", "П.к. Клодт"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал повесть «Кондуит и Швамбрания»?','["Чон Чжу-ён", "Леонардо Да Винчи", "Лев Кассиль", "Павел Дуров"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал роман «Три товарища»?','["Роланд Эммерих", "Nazareth", "Scooter", "Эрих Мария Ремарк"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал роман «Чёрный обелиск»?','["Эрида", "The Rembrandts", "Юрием Всеволодовичем", "Эрих Мария Ремарк"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал картину «Последний день Помпеи»?','["Карл Павлович Брюллов", "Август Хорьх", "Василий Iii", "Евгений Карелов"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал картину «Утро стрелецкой казни»?','["Василий Иванович Суриков", "Юрий Долгорукий", "В. А. Жуковский", "Август Хорьх"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал картину «Джоконда» («Мона Лиза»)?','["Леонардо да Винчи", "Томас Винтерберг", "Бетховен", "Guns N'' Roses"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал картину «Девочка с персиками»?','["Валентин Александрович Серов", "Маринина", "Балабанов", "Киитиро Тоёда"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране проводился 18-й чемпионат мира по футболу 2006 года?','["Германия", "Казахстан", "Израиль", "Канада"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какому композитору пришлось дописать оперу Мусоргского Хованщина?','["Лев Кассиль", "Георгий Данелия", "Римский-Корсаков", "Александр Дюма"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится город Борисполь?','["Кения", "Ирландия", "Украина", "Германия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Чей "Логико-философский трактат" вдохновил Венский кружок на создание программы логического позитивизма?','["Людвиг Витгенштейн", "Шекспир", "Томас Манн", "Малевич"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является административной столицей Юар?','["Сакраменто", "Сан-Хуан", "Ижевск", "Претория"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей штата Сша Кентукки?','["Франкфорт", "Под Смоленском", "Претория", "Кёнигсхайн-Видерау"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране расположены Семь Рильских озёр?','["Палау", "Болгария", "Ссср", "Мьянма"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем по образованию является солист группы "ддт" Юрий Шевчук?','["Скрипка", "Художник", "Джимми Стюарт", "Журналист"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какому государству сейчас принадлежит Тибет?','["Колумбия", "Ангола", "Швейцария", "Китаю"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой социалистической стране в декабре 1981 года было введено военное положение?','["Польша", "Австралия", "Латвия", "Палау"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был Томас Дилан, фамилию которого в качестве псевдонима взял американский композитор, музыкант и певец Роберт Циммерман?','["М. Ю. Лермонтова", "Летчик", "Философ", "Поэт"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая страна является родиной сыра "Пармезан"?','["Панама", "Голландия", "Италия", "Болгария"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор романа "Остров Крым"?','["Роланд Эммерих", "В. Аксенов", "Г.Юнгвальд-Хилькевич", "Михаил Булгаков"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто из героев «Сильмариллиона» создал Сильмариллы?','["Агата", "Тургенев", "Bad Boys Blue", "Феанор"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился Саади?','["Академия художеств", "Мар-дель-Плата", "Шираз", "Амьен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город представляет швейцарский футбольный клуб «Грассхоппер»?','["Таганрог", "Цюрих", "Спартак", "Севилья"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется административный центр китайской провинции Цинхай?','["Неаполь", "Браззавиль", "Синин", "Воткинск"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта Лариса Латынина завоевала 18 олимпийских медалей?','["Бейсболом", "Фехтование", "Спортивная гимнастика", "Футбол"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Каково местоположение Пирамиды Джосера, построенной Имхотепом?','["Пенсильвания", "Макао", "Саккара", "Питер"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится замок Нойшванштайн?','["Монголия", "Германия", "Колумбия", "Афганистан"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город был родным для чемпиона мира по шахматам Михаила Таля?','["Женева", "Константинополь", "Рига", "Братислава"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится город Эйзенах?','["Свободное государство Тюрингия", "Волгоград", "Сан-Франциско", "Оренбургская"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был режиссером самого знаменитого фильма о «Титанике»?','["Арам Ильич Хачатупян", "Кевин Костнер", "Георгий Данелия", "Джеймс Камерон"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране расположен знаменитый пляж Копакабана?','["Куба", "Италия", "Бразилия", "Панама"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой писатель является автором фантастической повести "Обмен разумов"?','["Л.Гайдай", "Р. Шекли", "Пол Анка", "Адольф Дасслер"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране сооружен мост Мира, спроектированный итальянским архитектором и французским дизайнером-осветителем?','["Грузия", "Италия", "Таиланд", "Новая Зеландия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком английском графстве находится город Ковентри?','["Уэст-Мидлендс", "Симферополь", "Токио", "Потсдам"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране проходили летние олимпийские игры 2000 года?','["Португалии", "Сша", "Перу", "Австралия (Сидней)"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране есть уникальная Долина кувшинов?','["Япония", "Во Франции в", "Лаос", "Монголия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто режиссер и главный герой фильма "Танцы с волками"?','["Цезарь", "Кевин Костнер", "Кэти Перри", "Марк Цукерберг"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор философского трактата "О природе вещей"?','["Тит Лукреций Кар", "Эрих Мария Ремарк", "Герберт Джордж Уэллс", "Хэнкс"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране имеют хождение тугрики?','["Ссср", "Аргентина", "Уругвай", "Монголия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой области находится город Бузулук?','["Ашхабаде", "Аризона", "Оренбургская", "Архангельская"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился Франциск Скорина — великий культурный деятель, белорусский первопечатник и просветитель?','["Чикаго", "Гаага", "Полоцк", "Кременчуг"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал поэму « Руслана и Людмила » ?','["Пушкин", "Чулпан Хаматова", "Эрих Мария Ремарк", "Александр Македонский"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был Святослав Рихтер?','["Поэт", "Скрипка", "Пианист", "Шут"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране существует Орден Академических пальм?','["Греция", "Австралия (Сидней)", "Ален Делон", "Франция"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто создал социальную сеть Facebook ?','["Марк Цукерберг", "П. И. Чайковский", "Nazareth", "Тит Лукреций Кар"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой из городов является столицей Мадагаскара?','["Неаполь", "Антананариву", "Москва-река", "Загреб"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Ботсваны?','["Габороне", "Вене", "Жодино", "Польша"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится город Фульда?','["Гондурас", "Юар", "Германия", "Кения"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой философ в «Первой речи против Катилины» упомянул крылатое выражение «О времена, о нравы»?','["Кевин Костнер", "Маринина", "Марк Цукерберг", "Цицерон"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какую страну представляет авиакомпания "Aer Lingus"?','["Грузия", "Ирландия", "Венесуэла", "Ангола"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Республики Конго?','["Браззавиль", "Лондон", "Загреб", "Благовещенск"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой художник является автором картины «Воины Апокалипсиса»?','["Ддт", "Виктор Васнецов", "М.Ю.Лермонтов", "Дмитрий Дмитриевич Шостакович"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто подбросил яблоко раздора Гере, Афине и Афродите?','["Эрида", "Юрием Всеволодовичем", "Юрий Долгорукий", "Алексей Пажитнов"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая актриса учредила собственный детский благотворительный фонд «Подари жизнь»?','["Бабель", "Гектор Берлиоз", "Эрида", "Чулпан Хаматова"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой рок-группе принадлежат альбом под названием «Собачья шерсть» («Hair of the Dog»)?','["Nazareth", "Константин Маковский", "Таривердиев", "Джефф Линн"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал "Краткую историю времени"?','["Марк Цукерберг", "Стивен Хокинг", "Карл Брюллов", "Михаил Булгаков"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе на Женевском озере провел последние годы жизни и был похоронен В.В.Набоков?','["Сша", "Монтрё", "Благовещенск", "Каракас"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Сыном какой страны был Кобо Абэ?','["Япония", "Швеция", "Перу", "Китаю"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая африканская страна является родиной предков Барака Обамы?','["Латвия", "Чили", "Мексика", "Кения"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране есть город Изюм?','["Грузия", "Украина", "Россия", "Швейцария"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой композитор написал «Лунную сонату»?','["Камиль Сен-Санс", "Адольф Дасслер", "Бетховен", "Эрих Мария Ремарк"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Капитаном какой московской футбольной команды был Игорь Нетто?','["Спартак", "Махачкала́", "Благовещенск", "Константинополь"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал книгу «Межзвёздный скиталец»?','["Джек Лондон", "Гектор Берлиоз", "Р.Брэдбери", "Артур конан дойл"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта слабовидящий кореец Им Дон Хьюн стал двукратным олимпийским чемпионом?','["Хоккей", "Стрельба из лука", "Сноуборд", "Айкидо"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой современный город в Крыму стоит на месте древнего греческого города Пантикапей?','["Макао", "Керчь", "Феодосия", "Ленинград"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал «Фантастическую симфонию» с посвящением: «Его Величеству Николаю I, императору Всероссийскому»?','["Алексей Учитель", "Кэти Перри", "Гектор Берлиоз", "Бабель"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране промышлял Голландец Шульц?','["Ален Делон", "Сша", "Колумбия", "Панама"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где родился Луи Армстронг?','["Тхимпху", "Олбани", "Нур-Султан", "Новый Орлеан"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Гражданство какой страны принял в 1982 году танцовщик Рудольф Нуриев после отказа вернуться в Ссср в 1961 году?','["Ссср", "Болгария", "Ален Делон", "Австрия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране родился танец хабанера?','["Куба", "Франции", "Саудовская Аравия", "Португалии"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал древнегреческую трагедию "Семеро против Фив"?','["Август Хорьх", "Эсхил", "Карл Брюллов", "Василий Иванович Суриков"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком российском городе в 2012 г. открыли памятник Юрию Деточкину?','["Самара", "Потсдам", "Мельбурн", "Архангельская"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится Суэцкий канал?','["Египет", "Швеция", "Венгрия", "Австралия (Сидней)"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был режиссёром фильма "Дом, в котором я живу"?','["Репин", "Мильтон", "Л. Кулиджанов", "Юрием Всеволодовичем"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится регион Пьемонт?','["Польша", "Венесуэла", "Италия", "Ангола"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился Иисус Христос?','["Канберра", "Академия художеств", "Москва-река", "Вифлеем"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится город Карачи?','["Голландия", "Ливия", "Пакистан", "Италия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором поэмы "Песнь о Гайавате"?','["Сименон", "Лонгфелло", "Эрида", "Людвиг Витгенштейн"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был режиссёром фильмов «Брат» и «Брат 2»?','["Дягилев", "Балабанов", "Филипп Добрый", "Хейердал"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится Озеро Медуз?','["Австрия", "Португалии", "Палау", "Финляндия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал "Историю села Горюхина"?','["Стивен Хокинг", "Пушкин", "Адам Опель", "Р.Брэдбери"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе прошел Чемпионат мира по водным видам спорта в 2011 году?','["Нью Йорк", "Шанхай", "Мальмё", "Кентукки"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где производятся пистолеты марки "Беретта"?','["Индия", "Италия", "Ливия", "Ален Делон"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком штате Сша находится Большое Солёное озеро?','["Юта", "Ленинград", "Аризона", "Мальмё"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был режиссером телесериала «Два капитана» 1976 года по знаменитому роману В. Каверина?','["В.Даль", "Марк Витрувий Поллион", "Евгений Карелов", "Роланд Эммерих"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто в 1430 году учредил орден Золотого руна?','["Милн", "Филипп Добрый", "Феанор", "Шишков В"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране проходили зимние Олимпийские игры 2002 года?','["Непал", "Кения", "Сша", "Италия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой страной более 40 лет правил Муаммар Каддафи?','["Великобритания.", "Гаити", "Австрия", "Ливия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится старинный жилой квартал и историко-архитектурный заповедник Ичери-шехер со знаменитой Девичьей башней и комплексом Дворца Ширваншахов?','["Самара", "Южная Дакота", "Баку", "Кентукки"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является создателем игры Тетрис?','["Виктор Васнецов", "Джеймс Кэмерон", "Хейердал", "Алексей Пажитнов"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был по профессии сказочный Урфин Джюс?','["Художник", "Джим Кэрри", "Столяр", "Балет"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой крымский город построен на месте существовавшего в Iii-ii вв до н. э. Неаполя Скифского?','["Удмуртия", "Лондон", "Нью-Йорк", "Симферополь"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город был столицей Королевства Обеих Сицилий, существовавшего в Xix веке?','["Претория", "Неаполь", "Бухарест", "Вологда"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая страна является местом проведения Зимних Олимпийских игр 2018 года?','["Шотландия", "Соединенные Штаты Америки", "Корея", "Франция"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта преуспел Марат Сафин?','["Хоккей с шайбой", "Теннис", "Стрельба из лука", "Фехтование"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является лидером-вокалистом британской рок-группы "Electric Light Orchestra"?','["Джефф Линн", "Джон Сингер Сарджент", "Стивен Спилберг", "Адам Опель"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился советский писатель Валентин Пикуль?','["Вифлеем", "Самарканд", "Калининград", "Ленинград"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится дворец Сан-Суси?','["Сан-Франциско", "Токио", "Уэст-Мидлендс", "Потсдам"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой области находится город Измаил?','["Шанхай", "Токио", "Нью Йорк", "Одесская"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится одна из старейших в Европе Амброзианская библиотека?','["Милан", "Питер", "Аризона", "Одесская"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является административным центром штата Калифорния, расположенного в Сша?','["Грац", "Шираз", "Академия художеств", "Сакраменто"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой из городов является столицей Камеруна?','["Эдинбург", "Яунде", "Росарио", "Теночтитлан"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Откуда родом известный модный дизайнер Каролина Херрера?','["Улан-Удэ", "Калининград", "Магас", "Венесуэлла"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город был столицей Оранжевого Свободного Государства?','["Литл-Рок", "Блумфонтейн", "Нижний Новгород", "Москва-река"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится памятник природы «Туннель Любви»?','["Афганистан", "Украина", "Лаос", "Венесуэла"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Чьим режиссерским дебютом стал фильм "Дуэлянты", рассказывающий о растянувшемся на 15 лет поединке двух гусарских офицеров?','["Александр Иванович Серый", "Алексей Пажитнов", "Булычев", "Ридли Скотта"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор романа "Грозовой перевал"?','["Эмили Бронте", "Малевич", "Есенин", "Гауф"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится знаменитая пагода Шведагон (98-метровая позолоченная ступа)?','["Индия", "Мьянма", "Шотландия", "Израиль"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране принята денежная единица "лари"?','["Грузия", "Лян", "Ален Делон", "Пакистан"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится город Учкудук?','["Иордания", "Узбекистан", "Швеция", "Гаити"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой античный учёный является автором трактата "Об архитектуре", где были описаны основные пропорции мужского тела?','["Марк Витрувий Поллион", "Эрих Мария Ремарк", "Г. Бичер-Стоу", "Римский-Корсаков"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком испанском городе был рожден и похоронен Сальвадор Дали?','["Фигерас", "Загреб", "Константинополь", "Москва"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится город Дарвин?','["Кения", "Австралия", "Франция", "Украина"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем была Има Сумак?','["Крокодилом", "Балет", "Философ", "Певицей"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Президентом какой страны был Даниэль Ортега с 1985 по 1990 годы?','["Саудовская Аравия", "Никарагуа", "Япония", "Монголия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе Минской области находится Белорусский автомобильный завод?','["Магас", "Жодино", "Таганрог", "Ахен"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой комик сыграл в кино Гринча — похитителя Рождества?','["Гамлет", "Родари", "Джим Кэрри", "Шишков В"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал картину "Видение отроку Варфоломею"?','["Михаил Нестеров", "Карл Бенц", "Игорь Масленников", "Рихард Штраус"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился знаменитый аргентинский композитор Астор Пьяццолла?','["Мар-дель-Плата", "Ижевск", "Москва-река", "Страсбург"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе Сша находится главный Зал и музей славы рок-н-ролла?','["Кливленд", "Феодосия", "Мальмё", "Питер"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какую страну представляет авиакомпания "Qantas" (Квонтас)?','["Австралия", "Узбекистан", "Казахстан", "Монголия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто после круиза по Тихому океану написал повесть «Путешествие на "Снарке"»?','["Джек Лондон", "Мольер", "Камиль Сен-Санс", "Кэти Перри"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая рок-группа создала хит "Don''t Cry"?','["Guns N'' Roses", "Георгий Данелия", "Шекспир", "Александр Иванович Серый"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал портрет полковника лейб-гвардии Гусарского полка Евграфа Давыдова, долгое время считавшийся изображением Дениса Давыдова?','["Сергей Прокофьев", "Айзек Азимов", "Орест Кипренский", "Маринина"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор картины «Смерть Ивана Грозного»?','["Хейердал", "У Чэнъэнь", "Константин Маковский", "Леонардо да Винчи"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится самая высокая статуя Будды в мире?','["Венгрия", "Канада", "Китай", "Израиль"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был основателем и первым редактором журнала "Отечественные записки"?','["Рихард Штраус", "Павел Свиньин", "М.Ю.Лермонтов", "Академия художеств"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является режиссером и комедии «Дети Дон Кихота», и военной драмы «Служили два товарища», и приключенческого фильма «Два капитана»?','["Лев Кассиль", "Сергей Юткевич", "Л. Кулиджанов", "Евгений Карелов"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране в 1973 году генерал Аугусто Пиночет осуществил военный переворот?','["Чили", "Португалии", "Франции", "Палау"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился актёр Алексей Баталов?','["Владимир", "Ситка", "Тхимпху", "Нево"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе Аргентины родился Эрнесто Че Гевара?','["Благовещенск", "Росарио", "Москва", "Абу-даби"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится самый широкий водопад в Европе Вентас румба?','["Узбекистан", "Латвия", "Ирландия", "Италия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором оперы «Танкред», написанной по одноимённой драме Вольтера?','["Ярослав Мудрый", "Джоаккино Россини", "Григорий Засекин", "Black Sabbath"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какому государству принадлежит остров Занзибар?','["Танзания", "Иордания", "Китай", "Голландия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город был столицей толкиеновского Гондора?','["Минас Тирит", "Таллин", "Канберра", "Кёнигсхайн-Видерау"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто из детских писателей написал книгу "От двух до пяти"?','["Корней Чуковский", "Вирджиния Вулф", "Р.Брэдбери", "Кэти Перри"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой известный певец исполнил песню «Prisencolinensinainciusol» в стиле речитатива?','["Леонардо да Винчи", "Камиль Сен-Санс", "Guns N'' Roses", "Адриано Челентано"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой легендарной рок-группе принадлежит культовый альбом «Sabotage» (1975)?','["Кевин Костнер", "Хачатурян", "Black Sabbath", "Мадонна"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется областной центр Закарпатской области Украины?','["Ужгород", "Ситка", "Батон-Руж", "Кёнигсхайн-Видерау"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был режиссёром художественного фильма-коллажа "Маяковский смеётся или Клоп-75"?','["Сергей Юткевич", "Джеймс Камерон", "Владимиром Святославичем", "Иван Андреевич Крылов"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родился В. В. Набоков?','["Москва", "Екатеринбург", "Монтрё", "Санкт-Петербург"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор и первый исполнитель шлягера «My Way»?','["Джеймс Камерон", "Адольф Дасслер", "Пол Анка", "Джек Лондон"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется столица Канады?','["Магас", "Оттава", "Эдинбург", "Цюрих"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране вручается кинопремия "Сезар"?','["Уругвай", "Швейцария", "Таиланд", "Франция"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе расположена знаменитая скульптура "Родина-мать"?','["Удмуртия", "Свободное государство Тюрингия", "Волгоград", "Оренбургская"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Удмуртии?','["Кёнигсхайн-Видерау", "Нижний Новгород", "Ижевск", "Чебоксары"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой писатель является автором знаменитого романа "451 градус по Фаренгейту"?','["Р.Брэдбери", "Булычев", "Eurythmics", "Марк Витрувий Поллион"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране правил царь Давид Строитель?','["Грузия", "Ирак", "Пакистан", "Италия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является основателем знаменитой соцсети "Вконтакте"?','["Мадонна", "Павел Дуров", "Eurythmics", "М.Ю.Лермонтов"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой немецкий писатель является автором новеллы «Смерть в Венеции», повествующей о любви писателя Густава фон Ашенбаха к мальчику Тадзио?','["Scooter", "Римский-Корсаков", "Томас Манн", "Олег Семёнович Кваша"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком командном виде спорта разыгрывается приз "Кубок Гагарина"?','["Хоккей с шайбой", "Дзюдо", "Бейсболом", "Теннис"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране расположен священный город Мачу Пикчу?','["Перу", "Австралия (Сидней)", "Ангола", "Швеция"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе родилась Цеткин?','["Китай", "Мар-дель-Плата", "Заксенхаузен", "Кёнигсхайн-Видерау"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится пирамида Солнца?','["Египет", "Швеция", "Голландия", "Мексика"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором музыки к фильму «Три плюс два»?','["У Чэнъэнь", "Наутилус Помпилиус", "Август Хорьх", "Андрей волконский"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал историю о Шерлоке Холмсе?','["Дмитрий Дмитриевич Шостакович", "Гауф", "Артур конан дойл", "Микеланджело"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('О каком виде спорта повествует фэнтези-фильм с Кевином Костнером «Поле его мечты»?','["Сноуборд", "Спортивная гимнастика", "Хоккей с шайбой", "Бейсбол"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Объединенных Арабских Эмиратов?','["Абу-даби", "Иерусалим", "Фигерас", "Братислава"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как сейчас называется город, который под именем Ново-Архангельск являлся столицей Русской Америки?','["Берн", "Росарио", "Ситка", "Под Смоленском"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком французском городе родился мастер импрессионизма Пьер-Огюст Ренуар?','["Болонья", "Вологда", "Лимож", "Теночтитлан"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится штаб-квартира Международного комитета Красного Креста?','["Мекка", "Женева", "Сан-Хуан", "Вологда"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Словакии?','["Теночтитлан", "Абу-даби", "Братислава", "Габороне"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал "Одесские рассказы"?','["Иван Андреевич Крылов", "Бабель", "Шарль Бодлер", "Пилат и другие"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой композитор написал музыку к кинофильмам «Семнадцать мгновений весны» и «Ирония судьбы, или С лёгким паром!»?','["Таривердиев", "Артур конан дойл", "Дмитрий Дмитриевич Шостакович", "Шишков В"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('При каком российском правителе был основан Новодевичий монастырь в Москве?','["Лундгрен", "Василий Iii", "Леонардо да Винчи", "Братьями Гурьевыми"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором классического китайского романа "Путешествие на Запад"?','["Адольф Дасслер", "Владимир Меньшов", "Л.Гайдай", "У Чэнъэнь"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится областной музей изобразительных искусств имени М. А. Врубеля?','["Омск", "Уэст-Мидлендс", "Брюссель", "Волгоград"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где расположен Центральный военно-морской музей?','["Самара", "Тюрингия", "Юта", "Питер"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе расположен знаменитый парк «Мини-Европа»?','["Макао", "Брюссель", "Мельбурн", "Удмуртия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является административным центром Пуэрто-Рико?','["Сан-Хуан", "Ужгород", "Сша", "Монтрё"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране говорят на языке пушту?','["Ливия", "Мексика", "Турция", "Афганистан"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Шотландии?','["Вашингтон", "Сша", "Благовещенск", "Эдинбург"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится библейский зоопарк?','["Иерусалим", "Киров", "Уэст-Мидлендс", "Саккара"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком шведском городе расположен Turning Torso — самый высокий в Скандинавии небоскреб?','["Иерусалим", "Пенсильвания", "Саккара", "Мальмё"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал картину "Скачет красная конница из октябрьской столицы, на защиту советской границы"?','["Малевич", "Соловьев-Седой", "Микеланджело", "Николая Михайловича Карамзина"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('На какой горе, согласно Ветхому Завету, умер пророк Моисей?','["Владимир", "Алабама", "Нево", "Чикаго"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был первым исполнителем "Восточной песни"?','["Валерий Ободзинский", "Хэнкс", "Людвиг Витгенштейн", "Джоаккино Россини"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Португалии?','["Лиссабон", "Вологда", "Вифлеем", "Страсбург"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как звали поэта, воссоздавшего латышский героический эпос "Лачплесис"?','["Пумпур", "Корней Чуковский", "Иосиф Хейфиц", "Black Sabbath"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Новой Зеландии?','["Антананариву", "Вологда", "Веллингтон", "Лиссабон"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком государстве функции банка исполняет Институт религиозных дел?','["Ватикан", "Афганистан", "Мьянма", "Ирак"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город, которому Жюль Верн посвятил рассказ «Идеальный город», стал местом его смерти и захоронения?','["Нур-Султан", "Амьен", "Улан-Удэ", "Владимир"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является административным центром испанского автономного сообщества Андалусии?','["Новый Орлеан", "Шираз", "Благовещенск", "Севилья"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется столица Эстонии?','["Самарканд", "Неаполь", "Сан-Хуан", "Таллин"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Хорватии?','["Казань", "Загреб", "Владимир", "Чебоксары"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой британский нововолновый дуэт исполнял популярный хит «Video Killed the Radio Star» («Видео погубило звезду радио»)?','["Сергей Юткевич", "The Buggles", "Айзек Азимов", "Алексей Пажитнов"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая поп-группа получила мировую известность, исполнив песню "You’re a Woman"?','["Киитиро Тоёда", "Сергей Сергеевич Прокофьев", "Bad Boys Blue", "Ханс Кристиан Андерсен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор романа "Дубровский"?','["Джефф Линн", "Питера Фаррелли", "Guns N'' Roses", "Пушкин"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Президентом какой страны был Нельсон Мандела, признанный лучшим Санта-Клаусом 1996 года?','["Латвия", "Камбоджа", "Соединенные Штаты Америки", "Юар"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком итальянском городе родился Никколо Паганини?','["Кигали", "Казань", "Генуя", "Женева"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране ежегодно проводится Международный Канский видеофестиваль?','["Япония", "Англия", "Грузия", "Россия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где протекает река Потомак?','["Швейцария", "Афганистан", "Ирак", "Сша"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Бутана?','["Джуно", "Магас", "Тхимпху", "Мбабане"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта четыре раза становился олимпийским чемпионом Виктор Кровопусков?','["Бейсболом", "Фехтование", "Теннис", "Стрельба из лука"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая страна - родина гуляша?','["Ссср", "Венгрия", "Уругвай", "Бразилия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе Ссср производили автомобили КрАЗ?','["Ужгород", "Яунде", "Габороне", "Кременчуг"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм "Первый учитель"?','["Андрей Кончаловский", "Наутилус Помпилиус", "В. А. Жуковский", "Владимир Меньшов"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем работал в зоопарке Крокодил Гена?','["Крокодилом", "Нотариусом", "Столяр", "Певицей"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто сыграл главного героя в фильме "Форрест Гамп"?','["Милн", "Константин Маковский", "Джек Лондон", "Хэнкс"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где родилась топ-модель Наоми Кэмпбелл?','["Сакраменто", "Вологда", "Великобритания", "Мбабане"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится дом-музей Анны Франк?','["Лондон", "Брюссель", "Одесская", "Амстердам"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая страна – родина саксофона?','["Бельгия", "Палау", "Ливия", "Португалия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой американский город сделал звезду из баскетболиста Майкла Джордана?','["Лиссабон", "Венесуэлла", "Грац", "Чикаго"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой инвентарь используют на Олимпийских играх спортсмены, соревнующиеся в хаф-пайпе?','["Хоккей с шайбой", "Дзюдо", "Футбол", "Сноуборд"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе Тамерлан основал столицу своего государства?','["Вологда", "Вене", "Колумбия", "Самарканд"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем по профессии был отец Леонардо да Винчи?','["Балет", "Художник", "Скрипка", "Нотариусом"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где расположена штаб-квартира Совета Европы?','["Страсбург", "Махачкала́", "Иерусалим", "Владимир"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится штаб-квартира авто-завода Бмв?','["Мюнхен", "Юта", "Макао", "Южная Дакота"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится Статуя Свободы?','["Амстердам", "Симферополь", "Свободное государство Тюрингия", "Нью Йорк"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город стоял на месте столицы Мексики?','["Венесуэлла", "Степанакерт", "Рига", "Теночтитлан"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране хранится международный эталон килограмма?','["Аргентина", "Франция", "Шотландия", "Китаю"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой областной центр знаменит дымковской игрушкой?','["Аризона", "Шанхай", "Киров", "Феодосия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой музыкальный инструмент прославил Ванессу Мэй?','["Царем Эпира", "Скрипка", "Философом", "М. Ю. Лермонтова"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Из какой страны родом танец летка-енка?','["Финляндия", "Украина", "Япония", "Испания"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как называется американская поп-группа, более всего известная по саундтреку к телесериалу «Друзья»?','["Айзек Азимов", "Томас Винтерберг", "Декарт", "The Rembrandts"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране родился и вырос Че Гевара?','["Финляндия", "Сша", "Аргентина", "Мексика"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком регионе России находится один из полюсов холода Северного полушария?','["Якутия", "Одесская", "Ленинград", "Баку"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране основная денежная единица называется Боливар?','["Италия", "Таиланд", "Венесуэла", "Венгрия"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране возникла рэп-музыка?','["Ссср", "Никарагуа", "Канада", "Сша"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как сейчас называется город, в котором родился и прожил всю жизнь немецкий философ Иммануил Кант?','["Браззавиль", "Бужумбура", "Калининград", "Екатеринбург"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какому искусству посвятил себя Вацлав Нижинский?','["Балет", "Журналист", "Столяр", "Нотариусом"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком австрийском городе родился Арнольд Шварценеггер?','["Рига", "Неаполь", "Грац", "Женева"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе проходит Открытый чемпионат Австралии по теннису?','["Кентукки", "Мадрид", "Киров", "Мельбурн"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Команда какой страны стала победительницей первого чемпионата мира по футболу?','["Уругвай", "Сша", "Шри-Ланка", "Гаити"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране состоялся чемпионат Европы по футболу в 2004 г.?','["Австрия", "Португалия", "Мексика", "Афганистан"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Действие какой пьесы Шекспира происходит в Эльсиноре?','["Гамлет", "Black Sabbath", "Марк Витрувий Поллион", "Г. Бичер-Стоу"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где погиб в авиакатастрофе польский президент Лех Качиньский в 2010 году?','["Под Смоленском", "Батон-Руж", "Мекка", "Спартак"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой фильм снял польский режиссер А. Вайда по мотивам романа М. Булгакова «Мастер и Маргарита»?','["Есенин", "Филипп Добрый", "Йозеф Гайдн", "Пилат и другие"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто из французских актеров сыграл в фильме "Тегеран-43"?','["Пакистан", "Шри-Ланка", "Ален Делон", "Лян"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как фамилия американского режиссёра, снявшего фильмы "Спартак" и "Лолита"?','["Кубрик", "Вирджиния Вулф", "Джефф Линн", "Таривердиев"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какое направление в живописи основал Казимир Малевич?','["Наутилус Помпилиус", "Олег Семёнович Кваша", "Супрематизм", "Михаил Михайлович Козаков"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой военной профессией владели президент Израиля Эзер Вейцман и президент Египта Хосни Мубарак?','["Скрипка", "Философ", "Художник", "Летчик"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране родился Николай Коперник?','["Англия", "Канада", "Польша", "Китай"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране родился Габриэль Гарсиа Маркес?','["Китаю", "Колумбия", "Кения", "Шри-Ланка"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая страна является родиной танца "краковяк"?','["Швейцария", "Палау", "Польша", "Лян"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какую оперу на сюжет «Ромео и Джульетты» написал композитор Винченцо Беллини?','["Григорий Засекин", "Джеймс Камерон", "Капулетти и Монтекки", "Рихард Штраус"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором опер "Кавалер розы" и "Женщина без тени"?','["Рихард Штраус", "Камиль Сен-Санс", "Иероним Босх", "Римский-Корсаков"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором слов и музыки гимна Индии?','["У Чэнъэнь", "Александр Македонский", "Рабиндранат Тагор", "Милн"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком штате Сша находятся гигантские вырезанные скульптурные портреты американских президентов?','["Макао", "Южная Дакота", "Токио", "Индия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Каким видом спорта занимался величайший игрок Нба Майкл Джордан во время перерыва в баскетбольной карьере?','["Хоккей с шайбой", "Спортивная гимнастика", "Стрельба из лука", "Бейсболом"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране родилась певица Мадонна?','["Сша", "Китай", "Непал", "Соединенные Штаты Америки"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто из лауреатов премии "Оскар" за лучшую мужскую роль в 1941 году стал летчиком-бомбардировщиком и дослужился до бригадного генерала?','["Философ", "Царем Эпира", "Джимми Стюарт", "Певицей"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Бурунди?','["Монтрё", "Сан-Хуан", "Каракас", "Бужумбура"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто составил "Толковый словарь живого великорусского языка"?','["Л.Гайдай", "Николая Михайловича Карамзина", "В.Даль", "Пумпур"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильмы "Космос как предчувствие", "Прогулка"?','["Р.Брэдбери", "Eurythmics", "Адам Опель", "Алексей Учитель"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Команда какой страны стала чемпионом Европы по футболу в 2000 г.?','["Австралия", "Кения", "Франция", "Аргентина"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране производится пиво Peroni?','["Корея", "Бельгия", "Италия", "Австралия (Сидней)"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какую фамилию носил почтальон из деревни Простоквашино?','["Балет", "Печкин", "Философ", "Крокодилом"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снялся в роли советского офицера Ивана Драги, противостоящего знаменитому боксеру Рокки?','["Лундгрен", "Маринина", "Кубрик", "Супрематизм"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто придумал Винни-Пуха и Пятачка?','["Феанор", "Милн", "Арам Ильич Хачатупян", "Квентин Тарантино"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране зародился буддизм?','["Индия", "Финляндия", "Аргентина", "Во Франции в"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта разыгрывают кубок Стэнли?','["Бейсбол", "Хоккей", "Спортивная гимнастика", "Стрельба из лука"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой области находятся Соловецкие острова?','["Аризона", "Свободное государство Тюрингия", "Архангельская", "Нью Йорк"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какому государству в Xvi веке принадлежал военный флот, вошедший в историю под названием "Непобедимая Армада"?','["Украина", "Испания", "Австралия (Сидней)", "Тайланд"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая страна является родиной кофе?','["Турция", "Ливия", "Эфиопия", "Юар"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто был сорежиссером Эльдара Рязанова на съемках фильма "Невероятные приключения итальянцев в России"?','["Поль Дюка", "Микеланджело", "Л.Гайдай", "Франко Проспери"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком штате находится город Херши и одноименная знаменитая американская компания по производству шоколада?','["Пенсильвания", "Потсдам", "Одесская", "Уэст-Мидлендс"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится скальный город Петра?','["Латвия", "Иордания", "Лян", "Австралия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был один из сильнейших противников Рима Пирр?','["Скрипка", "Столяр", "Царем Эпира", "Крокодилом"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком итальянском городе родился, жил и творил отец современной электрофизиологии Луиджи Гальвани?','["Воткинск", "Болонья", "Лимож", "Синин"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране была построена первая атомная электростанция?','["Ссср", "Австралия", "Россия", "Китай"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где находится Международный банк реконструкции и развития (мбрр)?','["Веллингтон", "Вашингтон", "Кременчуг", "Канберра"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какого поэта воспитала бабушка Елизавета Алексеевна Арсеньева?','["Балет", "Философ", "М. Ю. Лермонтова", "Царем Эпира"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится резиденция известной пивоваренной компании "Гиннесс"?','["Каракас", "Вологда", "Блумфонтейн", "Лондон"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Откуда родом был философ Конфуций?','["Чикаго", "Сакраменто", "Китай", "Спартак"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Что учредил в Санкт-Петербурге один из основателей Московского университета — русский меценат Иван Шувалов?','["Сша", "Владимир", "Академия художеств", "Абу-даби"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город был столицей государства Ашанти, существовавшего на территории современной Ганы с конца Xvii по начало XX века?','["Кумаси", "Ричмонд", "Бухарест", "Польша"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком концлагере трагически оборвалась жизнь старшего сына Иосифа Сталина?','["Степанакерт", "Заксенхаузен", "Тегеран", "Санкт-Петербург"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Как звали литературную маму сыщика-любителя Пуаро?','["Карл Павлович Брюллов", "Агата", "The Buggles", "Георгий Данелия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране находится город Ю?','["Непал", "Ливия", "Швеция", "Юар"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком городе находится самая высокая в мире телебашня?','["Брюссель", "Макао", "Токио", "Мюнхен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где родился Михаил Калашников?','["Нур-Султан", "Кумаси", "Чебоксары", "Курья"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где штаб-квартира Нато?','["Брюссельский столичный регион", "Константинополь", "Гаага", "Бужумбура"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая столица в Вирджинии?','["Бужумбура", "Таллин", "Росарио", "Ричмонд"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта разыгрывается Кубок Кремля?','["Дзюдо", "Теннис", "Хоккей с шайбой", "Бейсболом"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал Снежную королеву?','["Игорь Масленников", "Александр Иванович Серый", "Ханс Кристиан Андерсен", "С. Прокофьев"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто режиссер фильма Покровские ворота?','["Владимир Меньшов", "Михаил Михайлович Козаков", "Карл Брюллов", "Булычев"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто сочинил танец с саблями?','["Р.Брэдбери", "Артур конан дойл", "Арам Ильич Хачатупян", "Виктор Васнецов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Чей фильм Кин дза дза?','["Цезарь", "Джек Лондон", "Гамлет", "Георгий Данелия"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Чья композиция Беспечный ангел?','["Балабанов", "Стивен Спилберг", "Ария", "Валентин Александрович Серов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране зародились олимпийские игры?','["Сша", "Греция", "Казахстан", "Куба"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где родилась Пугачева?','["Аргентина", "Батон-Руж", "Москва", "Яунде"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где родился Децл?','["Благовещенск", "Амьен", "Кумаси", "Москва"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где родился Иисус Христос?','["Ахен", "Ижевск", "Чикаго", "Вифлеем"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где родился Чайковский?','["Минас Тирит", "Джуно", "Абуджа", "Воткинск"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая группа исполняет песню How much is the fish?','["Тит Лукреций Кар", "Scooter", "П.к. Клодт", "Лев Кассиль"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая столица в Великобритании?','["Лондон", "Мбабане", "Бужумбура", "Блумфонтейн"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая столица в Византии?','["Батон-Руж", "Таллин", "Минас Тирит", "Константинополь"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая столица Венесуэлы?','["Загреб", "Минас Тирит", "Каракас", "Монтрё"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая столица Вологодской области?','["Берн", "Ижевск", "Вологда", "Цюрих"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая столица Вьетнама?','["Абуджа", "Цюрих", "Ханой", "Нево"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто исполняет песню Material girl?','["Михаил Нестеров", "Адольф Дасслер", "М.Ю.Лермонтов", "Мадонна"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал басню Лебедь щука и рак?','["Олег Семёнович Кваша", "Иван Андреевич Крылов", "Эмили Бронте", "Мильтон"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто написал Человека-невидимку?','["Адам Опель", "Рихард Штраус", "Герберт Джордж Уэллс", "Андрей Дубенский"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто организовал компанию Mercedes?','["Иван Андреевич Крылов", "Михаил Булгаков", "Александр Македонский", "Карл Бенц"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто основал компанию Мерседес?','["Агата", "Кубрик", "Владимир Меньшов", "Карл Бенц"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял Титаник?','["Пилат и другие", "Джеймс Кэмерон", "Джоаккино Россини", "Сергей Прокофьев"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором сказки Аленький цветочек?','["Квентин Тарантино", "Гамлет", "Сергей Тимофеевич Аксаков", "Ханс Кристиан Андерсен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором труда История государства Российского?','["Иван Андреевич Крылов", "Герберт Джордж Уэллс", "Николая Михайловича Карамзина", "Лев Кассиль"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Чей фильм Зеленая книга?','["Балабанов", "Айзек Азимов", "Питера Фаррелли", "Поль Дюка"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Чья песня Sweet dreams?','["Август Хорьх", "Сергей Юткевич", "Эрида", "Eurythmics"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Чья песня Зеленоглазое такси?','["Эсхил", "Рихард Штраус", "Владимиром Святославичем", "Олег Семёнович Кваша"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто создал компанию Адидас?','["Адольф Дасслер", "Казимир Северинович Малевич", "Цезарь", "Гектор Берлиоз"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Джанго освобожденный?','["Кубрик", "Малевич", "Квентин Тарантино", "Лонгфелло"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Джентльмены удачи?','["Евгений Моргунов", "Eurythmics", "Александр Иванович Серый", "Михаил Булгаков"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Послезавтра?','["Александр Журбин", "Пилат и другие", "Роланд Эммерих", "Вирджиния Вулф"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Нижний Новгород?','["Лев Кассиль", "Константин Маковский", "Павел Свиньин", "Юрием Всеволодовичем"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто режиссер фильма Т 34?','["Алексей Сидоров", "The Rembrandts", "Ридли Скотт", "Маринина"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто режиссёр советской версии телесериала о Шерлоке Холмсе?','["Родари", "Михаил Булгаков", "Игорь Масленников", "Маринина"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Аватар?','["Родари", "Супрематизм", "Г. Бичер-Стоу", "Джеймс Кэмерон"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм в котором Джонни Депп сыграл роль Эдварда Руки ножницы?','["Л. Кулиджанов", "Эрида", "Павел Дуров", "Тим Бёртон"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Изгой?','["В. Аксенов", "Роберт Земекис", "Чон Чжу-ён", "М.Ю.Лермонтов"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Любовь и голуби?','["Эрих Мария Ремарк", "Владимир Меньшов", "Сергей Сергеевич Прокофьев", "Карл Брюллов"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Солдат Джейн?','["Маринина", "Л. Кулиджанов", "Ридли Скотт", "Константин Маковский"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Список Шиндлера?','["Александр Журбин", "Стивен Спилберг", "Джим Кэрри", "Игорь Масленников"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Чужой?','["Ридли Скотт", "Bad Boys Blue", "Арам Ильич Хачатупян", "Марк Витрувий Поллион"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто сочинил симфонию Ленинградскую?','["Дмитрий Дмитриевич Шостакович", "Соловьев-Седой", "Стивен Хокинг", "Сергей Юткевич"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком виде спорта прославился Евгений Кафельников?','["Хоккей", "Теннис", "Айкидо", "Футбол"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город столица республики Дагестан?','["Чикаго", "Махачкала́", "Под Смоленском", "Аргентина"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город столица республики Ингушетия?','["Магас", "Венесуэлла", "Росарио", "Шираз"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город столица республики Татарстан?','["Веллингтон", "Казань", "Нево", "Грац"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город столица штата Арканзас?','["Литл-Рок", "Остин", "Под Смоленском", "Блумфонтейн"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто сочинил симфонию Классическую?','["Кэти Перри", "Георгий Данелия", "Братьями Гурьевыми", "Сергей Сергеевич Прокофьев"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто сочинил симфонию Прощальную?','["Хачатурян", "Агата", "Алексей Пажитнов", "Йозеф Гайдн"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором балета Золушка?','["Ф. И. Тютчев", "Сергей Прокофьев", "Роберт Земекис", "Хэнкс"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой столице дворец Огузхан?','["Самара", "Питер", "Пушкин.", "Ашхабаде"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой столице убили Грибоедова?','["Польша", "Фигерас", "Тегеран", "Генуя"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране зародился футбол?','["Англия", "Индия", "Во Франции в", "Непал"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какая группа исполняет песню Отель Калифорния?','["Eagles", "Малевич", "Роберт Земекис", "Евгений Карелов"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Израиля?','["Грац", "Константинополь", "Иерусалим", "Самарканд"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Казахстана?','["Абуджа", "Амьен", "Фигерас", "Нур-Султан"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей Канады?','["Лиссабон", "Остин", "Оттава", "Амьен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Какой город является столицей штата Луизиана?','["Ситка", "Батон-Руж", "Благовещенск", "Заксенхаузен"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто нарисовал Джоконду?','["Сергей Прокофьев", "Август Хорьх", "Леонардо да Винчи", "Соловьев-Седой"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто нарисовал картину Три богатыря?','["В. Аксенов", "Виктор Васнецов", "Август Хорьх", "Сергей Юткевич"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто основал компанию Тойота?','["Микеланджело", "Киитиро Тоёда", "Сергей Тимофеевич Аксаков", "Джоаккино Россини"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто снял фильм Курск?','["Карл Брюллов", "Владимир Меньшов", "Томас Винтерберг", "Ханс Кристиан Андерсен"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором картины Последний день Помпеи?','["Ханс Кристиан Андерсен", "Карл Брюллов", "Карл Бенц", "Людвиг Витгенштейн"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является автором стихотворения Зима недаром злится?','["Андрей Кончаловский", "Маринина", "Ф. И. Тютчев", "Сергей Юткевич"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране был создан баскетбол?','["Соединенные Штаты Америки", "Эфиопия", "Гаити", "Палау"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто нарисовал картину Девочка с персиками?','["Декарт", "Константин Маковский", "Валентин Александрович Серов", "Иван Андреевич Крылов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто автор картины Мона Лиза?','["Филипп Добрый", "Джеймс Камерон", "Поль Дюка", "Леонардо да Винчи"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто нарисовал черный квадрат?','["Корней Чуковский", "Томас Манн", "Казимир Северинович Малевич", "Г. П. Данилевский"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Владимир?','["Eurythmics", "Владимиром Святославичем", "Леонардо да Винчи", "Марк Витрувий Поллион"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Гурьев?','["Дягилев", "Братьями Гурьевыми", "Стивен Спилберг", "Андрей Кончаловский"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Юрьев?','["Ярослав Мудрый", "Харальд Iii", "Марк Цукерберг", "Иероним Босх"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Кострома?','["Г.Юнгвальд-Хилькевич", "Вирджиния Вулф", "Юрий Долгорукий", "Виктор Васнецов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Ростов-на-Дону?','["Олег Семёнович Кваша", "Л. Кулиджанов", "Елизавета Петровна", "Дмитрий Дмитриевич Шостакович"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране впервые возник сентиментализм?','["Англия", "Ливия", "Корея", "Бразилия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где сформировался импрессионизм как направление?','["Гаити", "Соединенные Штаты Америки", "Во Франции в", "Корея"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Где создали компас?','["Латвия", "Китай", "Танзания", "Саудовская Аравия"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В каком водоеме утопили Муму?','["Вологда", "Магас", "Белфаст", "Москва-река"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране зародился стиль рококо?','["Франция", "Австралия (Сидней)", "Великобритания.", "Грузия"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране зародился ренессанс?','["Ирак", "Италия", "Швеция", "Сша"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Ярославль?','["Михаил Михайлович Козаков", "Ярослав Мудрый", "Леонардо да Винчи", "Пушкин"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан Челябинск?','["Игорь Масленников", "Scooter", "Л. Кулиджанов", "Алексей Тевкелев"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем была основана Александрия?','["Александр Македонский", "Bad Boys Blue", "Василий Iii", "The Buggles"]'::jsonb,0,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кем был основан город Красноярск?','["Франко Проспери", "Томас Манн", "Андрей Дубенский", "Л.Гайдай"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто основал город Петрозаводск?','["Александр Васильевич", "В. Аксенов", "Пушкин", "Петр I"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является основателем Севастополя?','["Эрих Мария Ремарк", "Шекспир", "Фома Фомич Мекензи", "Иван Андреевич Крылов"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является основателем города Осло?','["Юрий Долгорукий", "Гектор Берлиоз", "Харальд Iii", "Eagles"]'::jsonb,2,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является основателем города Самара?','["Николая Михайловича Карамзина", "Григорий Засекин", "Филипп Добрый", "Рихард Штраус"]'::jsonb,1,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является основателем Владивостока?','["Джеймс Кэмерон", "Ддт", "Харальд Iii", "Николай Николаевич Муравьёв-Амурский"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('Кто является основателем Липецка?','["Вирджиния Вулф", "У Чэнъэнь", "Bad Boys Blue", "Петр I"]'::jsonb,3,1);
INSERT INTO rb_quiz (question,options,correct,points) VALUES ('В какой стране зародился дадаизм?','["Индия", "Швейцария", "Мьянма", "Мексика"]'::jsonb,1,1);
